handle missing pyhon plugin

diff --git a/script/generate b/script/generate
--- a/script/generate
+++ b/script/generate
@@ -1,10 +1,6 @@
 #!/usr/bin/env bash
 set -e
 
-PROTO_DIR="./protos"
-OUTPUT_DIR="./"
-PROTOC_ARGS="--python_out=$OUTPUT_DIR --grpc_out=$OUTPUT_DIR --plugin=protoc-gen-grpc=`which grpc_python_plugin`"
-
 command -v protoc >/dev/null 2>&1 || {
   echo "protoc not found!"
   echo "Install protocol buffers and grpc before continuing."
@@ -12,11 +8,22 @@ command -v protoc >/dev/null 2>&1 || {
   exit 1
 }
 
+command -v grpc_python_plugin >/dev/null 2>&1 || {
+  echo "python grpc plugin not found!"
+  echo "Install protoc and grpc before continuing."
+  echo "http://www.grpc.io/docs/#install-grpc"
+  exit 1
+}
+
+PROTO_DIR="./protos"
+OUTPUT_DIR="./"
+PROTOC_ARGS="--python_out=$OUTPUT_DIR --grpc_out=$OUTPUT_DIR --plugin=protoc-gen-grpc=`which grpc_python_plugin`"
+
 mkdir -p $OUTPUT_DIR
 
 for PROTO in $(find $PROTO_DIR -name "*.proto"); do
-  echo "generating: $PROTO"
+  echo "generating: $PROTO into $OUTPUT_DIR"
   protoc -I $PROTO_DIR $PROTOC_ARGS $PROTO
 done
 
-echo "done."
+echo "all done."
